# Generated by Django 3.2.9 on 2021-11-24 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_born', models.CharField(max_length=200)),
                ('date_of_death', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photo_artist/')),
                ('history', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('style', models.CharField(max_length=200)),
                ('discribe', models.TextField()),
                ('picture', models.ImageField(upload_to='pictures/')),
                ('date_of_create', models.CharField(max_length=200)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pictures_home.artist')),
            ],
        ),
    ]
